# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app

# Include any dependencies generated for this target.
include CMakeFiles/SmartCalc.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/SmartCalc.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/SmartCalc.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/SmartCalc.dir/flags.make

CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o: SmartCalc_autogen/mocs_compilation.cpp
CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o -MF CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o.d -o CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/SmartCalc_autogen/mocs_compilation.cpp

CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/SmartCalc_autogen/mocs_compilation.cpp > CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.i

CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/SmartCalc_autogen/mocs_compilation.cpp -o CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.s

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o: /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c
CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o -MF CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o.d -o CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c > CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.i

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c -o CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.s

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o: /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c
CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o -MF CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o.d -o CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c > CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.i

CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c -o CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.s

CMakeFiles/SmartCalc.dir/main.cpp.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/main.cpp.o: /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/main.cpp
CMakeFiles/SmartCalc.dir/main.cpp.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/SmartCalc.dir/main.cpp.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/main.cpp.o -MF CMakeFiles/SmartCalc.dir/main.cpp.o.d -o CMakeFiles/SmartCalc.dir/main.cpp.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/main.cpp

CMakeFiles/SmartCalc.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/SmartCalc.dir/main.cpp.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/main.cpp > CMakeFiles/SmartCalc.dir/main.cpp.i

CMakeFiles/SmartCalc.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/SmartCalc.dir/main.cpp.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/main.cpp -o CMakeFiles/SmartCalc.dir/main.cpp.s

CMakeFiles/SmartCalc.dir/smartcalc.cpp.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/smartcalc.cpp.o: /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/smartcalc.cpp
CMakeFiles/SmartCalc.dir/smartcalc.cpp.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/SmartCalc.dir/smartcalc.cpp.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/smartcalc.cpp.o -MF CMakeFiles/SmartCalc.dir/smartcalc.cpp.o.d -o CMakeFiles/SmartCalc.dir/smartcalc.cpp.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/smartcalc.cpp

CMakeFiles/SmartCalc.dir/smartcalc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/SmartCalc.dir/smartcalc.cpp.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/smartcalc.cpp > CMakeFiles/SmartCalc.dir/smartcalc.cpp.i

CMakeFiles/SmartCalc.dir/smartcalc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/SmartCalc.dir/smartcalc.cpp.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/smartcalc.cpp -o CMakeFiles/SmartCalc.dir/smartcalc.cpp.s

CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o: CMakeFiles/SmartCalc.dir/flags.make
CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o: /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/qcustomplot.cpp
CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o: CMakeFiles/SmartCalc.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o -MF CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o.d -o CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o -c /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/qcustomplot.cpp

CMakeFiles/SmartCalc.dir/qcustomplot.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/SmartCalc.dir/qcustomplot.cpp.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/qcustomplot.cpp > CMakeFiles/SmartCalc.dir/qcustomplot.cpp.i

CMakeFiles/SmartCalc.dir/qcustomplot.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/SmartCalc.dir/qcustomplot.cpp.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc/qcustomplot.cpp -o CMakeFiles/SmartCalc.dir/qcustomplot.cpp.s

# Object files for target SmartCalc
SmartCalc_OBJECTS = \
"CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o" \
"CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o" \
"CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o" \
"CMakeFiles/SmartCalc.dir/main.cpp.o" \
"CMakeFiles/SmartCalc.dir/smartcalc.cpp.o" \
"CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o"

# External object files for target SmartCalc
SmartCalc_EXTERNAL_OBJECTS =

SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/SmartCalc_autogen/mocs_compilation.cpp.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/calc.c.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/secondary.c.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/main.cpp.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/smartcalc.cpp.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/qcustomplot.cpp.o
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/build.make
SmartCalc.app/Contents/MacOS/SmartCalc: /usr/local/lib/QtPrintSupport.framework/Versions/A/QtPrintSupport
SmartCalc.app/Contents/MacOS/SmartCalc: /usr/local/lib/QtWidgets.framework/Versions/A/QtWidgets
SmartCalc.app/Contents/MacOS/SmartCalc: /usr/local/lib/QtGui.framework/Versions/A/QtGui
SmartCalc.app/Contents/MacOS/SmartCalc: /usr/local/lib/QtCore.framework/Versions/A/QtCore
SmartCalc.app/Contents/MacOS/SmartCalc: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libcups.tbd
SmartCalc.app/Contents/MacOS/SmartCalc: CMakeFiles/SmartCalc.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Linking CXX executable SmartCalc.app/Contents/MacOS/SmartCalc"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/SmartCalc.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/SmartCalc.dir/build: SmartCalc.app/Contents/MacOS/SmartCalc
.PHONY : CMakeFiles/SmartCalc.dir/build

CMakeFiles/SmartCalc.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/SmartCalc.dir/cmake_clean.cmake
.PHONY : CMakeFiles/SmartCalc.dir/clean

CMakeFiles/SmartCalc.dir/depend:
	cd /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/qt/SmartCalc /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app /Users/vinitama/Desktop/C7_SmartCalc_v1.0-0/src/app/CMakeFiles/SmartCalc.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/SmartCalc.dir/depend

